version: '2'

services :
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER=$USERNAME
      - REPO_PASS=$USERPASS

  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    hostname: Uglyboy
    ports:
      - 9000:9000
    volumes:
      - $CONFIG:/etc/nginx/conf.d/
      - $SSL:/etc/nginx/cert/

  samba:
    image: elswork/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - 137:137
      - 138:138
      - 139:139
      - 445:445
    volumes:
      - /mnt/public/samba:/share/samba
      - /mnt/public/Media:/share/Media
    command:
      - "-u"
      - "uglyboy:zudhr4ed"
      - "-s"
      - "分享:/share/samba:rw:uglyboy"
      - "-s"
      - "影视:/share/Media:rw:uglyboy"

volumes:
  portainer_data:
