############################################################
#
# Logger  You can filter anything betwen the []'s in the logger.
#
############################################################

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical

default: info
logs:
  homeassistant.components.sensor: debug
  custom_components.xiaomi_miio_airconditioningcompanion.climate: debug
  root: info