'1584430879962':
  alias: 测试语音
  sequence:
  - data:
      media_content_id: https://fdfs.xmcdn.com/group78/M0A/10/32/wKgO1l55wzTAkDLHABj-Z7PeYnw378.m4a
      media_content_type: audio/m4a
    entity_id: media_player.dlna_digital_media_renderer
    service: media_player.play_media
