version: '2'

volumes:
  mpd_data:
  mqtt_data:
  mqtt_log:

services :
  mpd:
    image: gists/mpd
    container_name: mpd
    restart: unless-stopped
    devices:
      - /dev/snd
    volumes:
      - ./conf/mpd.conf:/etc/mpd.conf
      - mpd_data:/var/lib/mpd/
    ports:
      - 6600:6600

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    volumes:
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  hass:
    image: homeassistant/home-assistant
    container_name: hass
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    #privileged: true
    volumes:
      - ./config:/config
    #network_mode: host
    ports:
      - 8123:8123

#  proxy-hass:
#    image: nginx:alpine
#    container_name: proxy-hass
#    restart: unless-stopped
#    ports:
#      - 8123:8123
#    volumes:
#      - ./conf/proxy.conf:/etc/nginx/conf.d/default.conf
#      - ./config/ssl/:/etc/nginx/cert/
#    depends_on:
#      - hass