#switch:
#  - platform: xiaomi_miio
#    host: 192.168.0.121
#    token: '00000000000000000000000000000000'

#vacuum:
#  - platform: xiaomi_miio
#    host: 192.168.0.104
#    token: 6e786e495036783046504e6c5833764d

#sensor:
#  - platform: mitemp_bt
#    mac: '4C:65:A8:D5:66:F8'
#    monitored_conditions:
#      - temperature
#      - humidity
#      - battery