
# ------------------------------------------------------------------------------ #
# 天猫精灵
# ------------------------------------------------------------------------------ #
aligenie:  
  expire_hours: 30 

# ------------------------------------------------------------------------------ #
# 侧边栏管理
# ------------------------------------------------------------------------------ #
ha_sidebar:
  sidebar_title: 侧边栏管理
  sidebar_icon: mdi:xbox-controller-menu
  tabs_name: 二级菜单
  tabs_icon: mdi:format-list-numbered