media_player:
  - name: 树莓派音箱
    platform: mpd
    host: uglyboy.cn

# Text to speech
tts:
  - platform: baidu
    app_id: 18156926
    api_key: QWqx8C8UfRmjXGWwrzYWTt59
    secret_key: uwljPhmfrfaLGFBonGVl9X7EatkhxDCX
    speed: 5
    pitch: 5
    volume: 15
    person: 0
