
# ------------------------------------------------------------------------------ #
# 日出日落 https://www.home-assistant.io/components/sun/
# ------------------------------------------------------------------------------ #
sun:

# ------------------------------------------------------------------------------ #
# 网络测速
# ------------------------------------------------------------------------------ #
speedtestdotnet:
  scan_interval:
    minutes: 360
  monitored_conditions:
    - ping
    - download
